<?php

namespace AppBundle\Repository;

/**
 * NextEpisodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NextEpisodeRepository extends \Doctrine\ORM\EntityRepository
{
}
