<?php

namespace AppBundle\Repository;

/**
 * ReminderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReminderRepository extends \Doctrine\ORM\EntityRepository
{

    public function getAllSeriesIds()
    {
        return $this->createQueryBuilder('r')
            ->select('r.seriesId')
            ->distinct(true)
            ->getQuery()
            ->getArrayResult();
    }

}
